### ISSUE TITLE
Sandwich Bot for BEP-20

### ISSUE THREAD

**Issue by sonicwil** [Abelaby/MEV_Sandwich_Bot_Blueprint#1]
Hello, do you have the open source for bep20? if possible add me on discord: wilsonic

**Comment by Abelaby** [comment]
Hey @sonicwil , thanks for reaching out , this was an old experiment by me, you can check out these resources:

[Youtube Channel(Not mine)](https://www.youtube.com/@merunasg/videos)
[Discord community -Solid Quant](https://discord.gg/Z3GsvnAk)
